name: CI Sandbox

on:
  push:
    branches: [ "main" ]

jobs:
  e2e-example:
    runs-on: ubuntu-latest
    container:
#      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
#     FirefoxにCJKをあらかじめインストールしたイメージを使う
      image: takeshiemoto/firefox-with-cjk:latest
      options: --user 1001
    steps:
      - name: Fonts
        run: apt-get update && apt-get install -y fontconfig fonts-noto-cjk
